-- =============================================================================
-- Imvite — reference schema sketch (PostgreSQL 16+)
--
-- This is a DESIGN ARTEFACT, not a migration. It exists to make the
-- relationships in 01-data-model.md concrete and reviewable. Real migrations
-- will be generated by Doctrine from entities.
--
-- Conventions:
--   * uuid PKs, UUIDv7 generated app-side (symfony/uid Uuid::v7()) so they are
--     time-ordered (good index locality) without leaking sequence counts.
--   * timestamptz everywhere; wall-clock is never stored naive.
--   * enums as text + CHECK rather than native ENUM types: adding a value to a
--     native enum is a schema change and they are painful to reorder.
--   * jsonb for validated structured content only, never as a dumping ground.
--     Every jsonb column below has a JSON Schema enforced at the app boundary.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- =============================================================================
-- IDENTITY
-- =============================================================================

CREATE TABLE users (
    id              uuid PRIMARY KEY,
    email           citext NOT NULL UNIQUE,
    password_hash   text,                        -- NULL => magic-link only
    display_name    text,
    country_code    char(2),                     -- last known BILLING country
    marketing_opt_in boolean NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

-- Authorisation goes through this table from day one, even though MVP only
-- ever writes one 'owner' row. Avoids a painful refactor when collaboration
-- lands in Phase 2.
CREATE TABLE invitation_collaborators (
    invitation_id   uuid NOT NULL,
    user_id         uuid NOT NULL REFERENCES users(id),
    role            text NOT NULL CHECK (role IN ('owner','editor','viewer')),
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (invitation_id, user_id)
);


-- =============================================================================
-- SEEDED CATALOGS  (no user data; display names live in translation catalogs)
-- =============================================================================

CREATE TABLE event_kinds (
    code                text PRIMARY KEY,     -- 'wedding','engagement','baptism',...
    family              text NOT NULL,        -- 'wedding','religious','coming_of_age','milestone'
    default_sections    jsonb NOT NULL,       -- ordered [{type, data}] starter set
    default_sub_events  jsonb NOT NULL,       -- e.g. ['ceremony','reception']
    sort_order          int  NOT NULL DEFAULT 0,
    is_active           boolean NOT NULL DEFAULT true
);

CREATE TABLE features (
    code            text PRIMARY KEY,         -- 'personalised_links','guest_limit',...
    value_type      text NOT NULL CHECK (value_type IN ('bool','int')),
    default_value   jsonb NOT NULL            -- what an unpaid draft gets
);

CREATE TABLE plans (
    code        text PRIMARY KEY,             -- 'basic','plus'
    grants      jsonb NOT NULL,               -- {feature_code: value}
    is_active   boolean NOT NULL DEFAULT true
);

CREATE TABLE price_points (
    id                  uuid PRIMARY KEY,
    sku                 text NOT NULL,        -- 'plan.plus','addon.remove_branding'
    band                text NOT NULL CHECK (band IN ('a','b','c')),
    currency            char(3) NOT NULL,
    amount_minor        int NOT NULL,         -- tax-INCLUSIVE for EU/UK display
    provider_price_id   text,                 -- MoR's own price id
    active_from         timestamptz NOT NULL DEFAULT now(),
    active_to           timestamptz
);
CREATE UNIQUE INDEX price_points_live_uq
    ON price_points (sku, band, currency) WHERE active_to IS NULL;


-- =============================================================================
-- THEMES
-- =============================================================================

CREATE TABLE themes (
    id                  uuid PRIMARY KEY,
    code                text NOT NULL UNIQUE,
    status              text NOT NULL CHECK (status IN ('draft','beta','published','retired')),
    current_version     int  NOT NULL,
    tier                text NOT NULL CHECK (tier IN ('standard','premium')),
    supported_sections  text[] NOT NULL,
    capabilities        jsonb NOT NULL,
    preview_assets      jsonb NOT NULL DEFAULT '{}',
    sort_order          int NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE theme_versions (
    theme_id            uuid NOT NULL REFERENCES themes(id),
    version             int  NOT NULL,
    manifest            jsonb NOT NULL,       -- validated against the manifest JSON Schema in CI
    asset_bundle_key    text NOT NULL,        -- IMMUTABLE per version; served with max-age=1y
    released_at         timestamptz NOT NULL DEFAULT now(),
    changelog           text,
    PRIMARY KEY (theme_id, version)
);


-- =============================================================================
-- INVITATIONS
-- =============================================================================

CREATE TABLE invitations (
    id                  uuid PRIMARY KEY,
    slug                citext NOT NULL UNIQUE,   -- CSPRNG-derived, never sequential
    status              text NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','published','archived','expired')),
    event_kind          text NOT NULL REFERENCES event_kinds(code),

    theme_id            uuid NOT NULL REFERENCES themes(id),
    theme_version       int  NOT NULL,            -- PINNED at publish; never auto-advanced
    palette_code        text,


    timezone            text NOT NULL,            -- IANA, e.g. 'Europe/Belgrade'

    rsvp_mode           text NOT NULL DEFAULT 'open'
                        CHECK (rsvp_mode IN ('open','invite_only','closed')),
    rsvp_deadline       timestamptz,
    passcode_hash       text,                     -- optional gate; default off
    allow_indexing      boolean NOT NULL DEFAULT false,  -- noindex by default

    content_hash        text NOT NULL DEFAULT '', -- sha256 of rendered content; OG + CDN key
    og_image_key        text,                     -- og/{id}/{content_hash}.jpg on R2
    og_generated_at     timestamptz,

    published_at        timestamptz,
    expires_at          timestamptz,              -- from the link_lifetime_days entitlement
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz,

    FOREIGN KEY (theme_id, theme_version) REFERENCES theme_versions(theme_id, version)
);

ALTER TABLE invitation_collaborators
    ADD CONSTRAINT invitation_collaborators_invitation_fk
    FOREIGN KEY (invitation_id) REFERENCES invitations(id) ON DELETE CASCADE;

CREATE INDEX invitations_status_idx ON invitations (status) WHERE deleted_at IS NULL;
CREATE INDEX invitations_expiry_idx ON invitations (expires_at) WHERE status = 'published';

-- Old slugs stay alive forever: they live in WhatsApp histories.
CREATE TABLE invitation_slug_aliases (
    slug            citext PRIMARY KEY,
    invitation_id   uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    created_at      timestamptz NOT NULL DEFAULT now()
);


-- =============================================================================
-- CONTENT
-- =============================================================================

CREATE TABLE invitation_sections (
    id              uuid PRIMARY KEY,
    invitation_id   uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    type            text NOT NULL,        -- fixed vocabulary; see 01-data-model.md §1.4
    position        int  NOT NULL,
    is_visible      boolean NOT NULL DEFAULT true,
    data            jsonb NOT NULL,       -- JSON Schema per section type
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX invitation_sections_order_idx ON invitation_sections (invitation_id, position);

CREATE TABLE venues (
    id                  uuid PRIMARY KEY,
    invitation_id       uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    name                text NOT NULL,
    address             text NOT NULL,    -- free text: address formats vary too much to normalise
    lat                 numeric(9,6),
    lng                 numeric(9,6),
    map_url             text,             -- host-pasted Google/Apple Maps link
    directions_note     text,
    position            int NOT NULL DEFAULT 0
);

CREATE TABLE invitation_events (          -- the sub-events / multi-day schedule
    id                  uuid PRIMARY KEY,
    invitation_id       uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    code                text NOT NULL,    -- 'ceremony','reception','rehearsal_dinner',...
    title               text,             -- overrides the catalog label
    description         text,
    starts_at           timestamptz NOT NULL,
    ends_at             timestamptz,
    timezone            text NOT NULL,    -- MAY differ from the invitation's
    is_time_tbc         boolean NOT NULL DEFAULT false,
    venue_id            uuid REFERENCES venues(id) ON DELETE SET NULL,
    dress_code          text,
    position            int NOT NULL DEFAULT 0,
    default_invited     boolean NOT NULL DEFAULT true,   -- overrides store exceptions only
    requires_rsvp       boolean NOT NULL DEFAULT true,
    capacity            int
);
CREATE INDEX invitation_events_idx ON invitation_events (invitation_id, starts_at);

CREATE TABLE media_assets (
    id                  uuid PRIMARY KEY,
    invitation_id       uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    kind                text NOT NULL CHECK (kind IN ('image','audio','video')),
    storage_key         text NOT NULL,
    mime                text NOT NULL,
    bytes               bigint NOT NULL,
    width               int,
    height              int,
    duration_ms         int,
    blurhash            text,
    focal_point         jsonb,            -- {"x":0.5,"y":0.33} for art-directed crops
    checksum            bytea,
    moderation_status   text NOT NULL DEFAULT 'ok'
                        CHECK (moderation_status IN ('pending','ok','flagged')),
    created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX media_assets_inv_idx ON media_assets (invitation_id, kind);


-- =============================================================================
-- GUESTS
-- =============================================================================

CREATE TABLE guest_groups (
    id                  uuid PRIMARY KEY,
    invitation_id       uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    label               text NOT NULL,        -- internal: "Familja Hoxha"
    greeting            text,                 -- what the guest sees
    token_hash          bytea NOT NULL,       -- sha256(token); a dump must not yield live links
    token_hint          char(4) NOT NULL,     -- last 4 chars, so the host can match a link to a row
    seats_allocated     int NOT NULL DEFAULT 1,
    allow_plus_one      boolean NOT NULL DEFAULT false,
    plus_one_limit      int NOT NULL DEFAULT 0,
    channel             text NOT NULL DEFAULT 'unknown'
                        CHECK (channel IN ('whatsapp','viber','telegram','sms','email','print','unknown')),
    phone_e164          text,
    email               citext,
    notes               text,
    imported_batch_id   uuid,                 -- lets a bad import be undone wholesale
    sent_at             timestamptz,          -- host marked "message sent"
    first_opened_at     timestamptz,
    review_status       text NOT NULL DEFAULT 'accepted'
                        CHECK (review_status IN ('accepted','pending_host_review','rejected')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz
);
CREATE UNIQUE INDEX guest_groups_token_uq ON guest_groups (token_hash);
CREATE INDEX guest_groups_inv_idx ON guest_groups (invitation_id) WHERE deleted_at IS NULL;
CREATE INDEX guest_groups_label_trgm ON guest_groups USING gin (label gin_trgm_ops);
CREATE INDEX guest_groups_batch_idx ON guest_groups (imported_batch_id);

CREATE TABLE guest_group_tags (
    guest_group_id  uuid NOT NULL REFERENCES guest_groups(id) ON DELETE CASCADE,
    tag             text NOT NULL,        -- 'family-bride','colleagues','village'
    PRIMARY KEY (guest_group_id, tag)
);

CREATE TABLE guests (
    id                  uuid PRIMARY KEY,
    guest_group_id      uuid NOT NULL REFERENCES guest_groups(id) ON DELETE CASCADE,
    full_name           text NOT NULL,    -- ONE field: "first/last" is a Western assumption
    age_band            text CHECK (age_band IN ('adult','child','infant')),
    attending           text NOT NULL DEFAULT 'pending'
                        CHECK (attending IN ('pending','yes','no','maybe')),
    meal_preference     text,             -- may be Art. 9 data; see 09-risks.md §9.5
    allergy_note        text,             -- ditto: consent + retention required
    added_by            text NOT NULL DEFAULT 'host' CHECK (added_by IN ('host','guest')),
    position            int NOT NULL DEFAULT 0,
    updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX guests_group_idx ON guests (guest_group_id);

-- Exceptions only. invited(group, event) = COALESCE(override, event.default_invited)
CREATE TABLE guest_event_overrides (
    guest_group_id      uuid NOT NULL REFERENCES guest_groups(id) ON DELETE CASCADE,
    invitation_event_id uuid NOT NULL REFERENCES invitation_events(id) ON DELETE CASCADE,
    invited             boolean NOT NULL,
    PRIMARY KEY (guest_group_id, invitation_event_id)
);

-- APPEND-ONLY. guests.attending is a materialised projection of this.
CREATE TABLE rsvp_submissions (
    id                  uuid PRIMARY KEY,
    invitation_id       uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    guest_group_id      uuid REFERENCES guest_groups(id) ON DELETE SET NULL,
    payload             jsonb NOT NULL,   -- the form exactly as received
    answers             jsonb NOT NULL DEFAULT '{}',
    source              text NOT NULL
                        CHECK (source IN ('personal_link','open_link','qr','host_manual','import')),
    ip_hash             bytea,            -- salted; rate limiting only, purge with PII
    user_agent_hash     bytea,
    consent_version     text,             -- which privacy text the guest was shown
    superseded_by       uuid REFERENCES rsvp_submissions(id),
    review_status       text NOT NULL DEFAULT 'accepted'
                        CHECK (review_status IN ('accepted','pending_host_review','rejected')),
    submitted_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX rsvp_submissions_inv_idx   ON rsvp_submissions (invitation_id, submitted_at DESC);
CREATE INDEX rsvp_submissions_group_idx ON rsvp_submissions (guest_group_id, submitted_at DESC);

CREATE TABLE rsvp_event_selections (
    submission_id       uuid NOT NULL REFERENCES rsvp_submissions(id) ON DELETE CASCADE,
    invitation_event_id uuid NOT NULL REFERENCES invitation_events(id) ON DELETE CASCADE,
    attending_count     int NOT NULL DEFAULT 0,
    PRIMARY KEY (submission_id, invitation_event_id)
);


-- =============================================================================
-- ORDERS AND ENTITLEMENTS
-- =============================================================================

CREATE TABLE orders (
    id                  uuid PRIMARY KEY,
    user_id             uuid NOT NULL REFERENCES users(id),
    invitation_id       uuid REFERENCES invitations(id),  -- NULL for planner credit packs
    provider            text NOT NULL
                        CHECK (provider IN ('paddle','fastspring','twocheckout','paypal','bank_transfer','manual')),
    provider_order_id   text NOT NULL,
    band                text NOT NULL CHECK (band IN ('a','b','c')),
    billing_country     char(2),          -- THE pricing authority; never IP, never a dropdown
    currency            char(3) NOT NULL,
    gross_minor         int NOT NULL,
    tax_minor           int NOT NULL DEFAULT 0,
    net_minor           int NOT NULL,
    status              text NOT NULL
                        CHECK (status IN ('pending','paid','refunded','partially_refunded','chargeback','failed')),
    invoice_url         text,
    withdrawal_waiver_at timestamptz,     -- EU 14-day right; log when the box was ticked
    raw_payload         jsonb NOT NULL,   -- webhook stored verbatim; you WILL need to replay
    purchased_at        timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_order_id)
);
CREATE INDEX orders_invitation_idx ON orders (invitation_id);

CREATE TABLE order_items (
    id                  uuid PRIMARY KEY,
    order_id            uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    sku                 text NOT NULL,
    quantity            int NOT NULL DEFAULT 1,
    unit_amount_minor   int NOT NULL
);

-- THE ONLY TABLE THE RENDER PATH MAY READ FOR FEATURE DECISIONS.
-- Recomputed idempotently by EntitlementResolver from orders + promos + manual grants.
CREATE TABLE invitation_entitlements (
    invitation_id   uuid NOT NULL REFERENCES invitations(id) ON DELETE CASCADE,
    feature_code    text NOT NULL REFERENCES features(code),
    value           jsonb NOT NULL,       -- true / 500 / 365
    source          text NOT NULL
                    CHECK (source IN ('default','plan','addon','promo','planner_credit','manual')),
    order_item_id   uuid REFERENCES order_items(id) ON DELETE SET NULL,
    granted_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz,
    PRIMARY KEY (invitation_id, feature_code)
);


-- =============================================================================
-- OPERATIONS
-- =============================================================================

-- Drives the retention job: purge guest PII N days after the last sub-event,
-- after offering the host an export. Ship this in the MVP (09-risks.md §9.5).
CREATE TABLE retention_schedule (
    invitation_id   uuid PRIMARY KEY REFERENCES invitations(id) ON DELETE CASCADE,
    purge_guests_at timestamptz NOT NULL,
    notified_at     timestamptz,
    purged_at       timestamptz
);

-- Minimal audit trail for support: "I definitely RSVP'd" tickets during
-- wedding week are answered from here.
CREATE TABLE audit_log (
    id              bigserial PRIMARY KEY,
    invitation_id   uuid,
    actor_user_id   uuid,
    action          text NOT NULL,
    context         jsonb NOT NULL DEFAULT '{}',
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_inv_idx ON audit_log (invitation_id, created_at DESC);
